-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 16:06:48 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `account_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_groups` ;

CREATE TABLE IF NOT EXISTS `account_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `display_name` VARCHAR(45) NULL,
  `security_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;

CREATE UNIQUE INDEX `security_role_UNIQUE` ON `account_groups` (`security_role` ASC);

CREATE UNIQUE INDEX `display_name_UNIQUE` ON `account_groups` (`display_name` ASC);


-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL,
  `activation_date` TIMESTAMP NULL DEFAULT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_account_account_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `account_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100;

CREATE INDEX `fk_account_account_group1_idx` ON `accounts` (`group_id` ASC);


-- -----------------------------------------------------
-- Table `contract_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contract_types` ;

CREATE TABLE IF NOT EXISTS `contract_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `countries` ;

CREATE TABLE IF NOT EXISTS `countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `programming_languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `programming_languages` ;

CREATE TABLE IF NOT EXISTS `programming_languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;


-- -----------------------------------------------------
-- Table `frameworks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `frameworks` ;

CREATE TABLE IF NOT EXISTS `frameworks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `programming_language_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_framework_programming_language2`
    FOREIGN KEY (`programming_language_id`)
    REFERENCES `programming_languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100;

CREATE INDEX `fk_framework_programming_language2_idx` ON `frameworks` (`programming_language_id` ASC);


-- -----------------------------------------------------
-- Table `profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profiles` ;

CREATE TABLE IF NOT EXISTS `profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zs_number` VARCHAR(32) NOT NULL,
  `main_pr_lng_id` INT NULL,
  `second_pr_lng_id` INT NULL,
  `test_rating` INT NULL,
  `origin_country_id` INT NULL,
  `visa_needed` TINYINT(1) NULL,
  `company_type` VARCHAR(20) NULL,
  `experience` INT NULL,
  `work_history` VARCHAR(500) NULL,
  `english_level` INT NULL,
  `travel_time` INT NULL,
  `preferred_city` VARCHAR(45) NULL,
  `availability` INT NULL,
  `hours_per_week` VARCHAR(45) NULL,
  `relocation_reason` VARCHAR(500) NULL,
  `contract_type_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_profile_programming_language1`
    FOREIGN KEY (`main_pr_lng_id`)
    REFERENCES `programming_languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_programming_language2`
    FOREIGN KEY (`second_pr_lng_id`)
    REFERENCES `programming_languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_country1`
    FOREIGN KEY (`origin_country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_contract_types1`
    FOREIGN KEY (`contract_type_id`)
    REFERENCES `contract_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100;

CREATE INDEX `fk_profile_programming_language1_idx` ON `profiles` (`main_pr_lng_id` ASC);

CREATE INDEX `fk_profile_programming_language2_idx` ON `profiles` (`second_pr_lng_id` ASC);

CREATE INDEX `fk_profile_country1_idx` ON `profiles` (`origin_country_id` ASC);

CREATE INDEX `fk_profiles_contract_types1_idx` ON `profiles` (`contract_type_id` ASC);


-- -----------------------------------------------------
-- Table `known_frameworks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `known_frameworks` ;

CREATE TABLE IF NOT EXISTS `known_frameworks` (
  `profile_id` INT NOT NULL,
  `framework_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `framework_id`),
  CONSTRAINT `fk_profile_framework_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_framework_framework1`
    FOREIGN KEY (`framework_id`)
    REFERENCES `frameworks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profile_framework_profile1_idx` ON `known_frameworks` (`profile_id` ASC);

CREATE INDEX `fk_profile_framework_framework1_idx` ON `known_frameworks` (`framework_id` ASC);


-- -----------------------------------------------------
-- Table `preferred_countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `preferred_countries` ;

CREATE TABLE IF NOT EXISTS `preferred_countries` (
  `profile_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `country_id`),
  CONSTRAINT `fk_preferred_countries_profiles1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferred_countries_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_preferred_countries_countries1_idx` ON `preferred_countries` (`country_id` ASC);


-- -----------------------------------------------------
-- Table `company_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company_types` ;

CREATE TABLE IF NOT EXISTS `company_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `company_types` (`name` ASC);


-- -----------------------------------------------------
-- Table `preferred_company_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `preferred_company_types` ;

CREATE TABLE IF NOT EXISTS `preferred_company_types` (
  `profile_id` INT NOT NULL,
  `company_type_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `company_type_id`),
  CONSTRAINT `fk_preferred_company_types_profiles1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferred_company_types_company_types1`
    FOREIGN KEY (`company_type_id`)
    REFERENCES `company_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_preferred_company_types_profiles1_idx` ON `preferred_company_types` (`profile_id` ASC);

CREATE INDEX `fk_preferred_company_types_company_types1_idx` ON `preferred_company_types` (`company_type_id` ASC);


-- -----------------------------------------------------
-- Table `role_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_types` ;

CREATE TABLE IF NOT EXISTS `role_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `role_types` (`name` ASC);


-- -----------------------------------------------------
-- Table `profile_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profile_roles` ;

CREATE TABLE IF NOT EXISTS `profile_roles` (
  `profile_id` INT NOT NULL,
  `role_type_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `role_type_id`),
  CONSTRAINT `fk_preferred_roles_profiles1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preferred_roles_role_types1`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `role_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_preferred_roles_profiles1_idx` ON `profile_roles` (`profile_id` ASC);

CREATE INDEX `fk_preferred_roles_role_types1_idx` ON `profile_roles` (`role_type_id` ASC);


-- -----------------------------------------------------
-- Table `rank_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rank_types` ;

CREATE TABLE IF NOT EXISTS `rank_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `rank_types` (`name` ASC);


-- -----------------------------------------------------
-- Table `profile_ranks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profile_ranks` ;

CREATE TABLE IF NOT EXISTS `profile_ranks` (
  `profile_id` INT NOT NULL,
  `rank_type_id` INT NOT NULL,
  PRIMARY KEY (`profile_id`, `rank_type_id`),
  CONSTRAINT `fk_profle_ranks_profiles1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profle_ranks_rank_types1`
    FOREIGN KEY (`rank_type_id`)
    REFERENCES `rank_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_profle_ranks_profiles1_idx` ON `profile_ranks` (`profile_id` ASC);

CREATE INDEX `fk_profle_ranks_rank_types1_idx` ON `profile_ranks` (`rank_type_id` ASC);


-- -----------------------------------------------------
-- Table `custom_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `custom_fields` ;

CREATE TABLE IF NOT EXISTS `custom_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` INT NOT NULL,
  `field_name` VARCHAR(100) NULL,
  `field_value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_custom_fields_profiles1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100;

CREATE INDEX `fk_custom_fields_profiles1_idx` ON `custom_fields` (`profile_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
